# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keshav Memorial Institute of Technology
email: info@kmit.in
description: > # this means to ignore newlines until "baseurl:"
  KMIT, established in year 2007 , is one of the premier engineering colleges in the state of Telangana. KMIT is sponsored by Keshav Memorial Education Society (KMES) ,well known in Hyderabad ,for the past 75 years, for running various educational institutions of repute.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kmit.in" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
facebook_username: kmit2

# Build settings
markdown: kramdown
